### ISSUE TITLE
About dotenv variables

### ISSUE THREAD

**Issue by piagja** [patobiskoto/bot_aavegotchi#1]
Hello man, how are you?

I'm trying to find a reliable Aavegotchi bot to maximize my profits, but I've found a lot of scam codes. I'm not sure, indeed, I use Linux and most programs didn't work with Wine.

There are one or two codes that have Github open codes.
I'm not here to steal or similar or even review your code. I just want to know about dotenv variables.

What are DIAMOND_ADDRESS, CRON_PATTERN, and ADDRESSES_TO_CHECK?
I think the first one is the GHST contract token? Or is it one of the minerals? (FUD, ALPHA, KEK, FOMO)

Cheers mate!

**Comment by patobiskoto** [comment]
Hi @piagja,

You can fork my project, no issue :)
For dotenv, I will write a readme to speak about that.
I'm using 6 env:

- JSON_RPC_PROVIDER : link to your dedicated RPC. I write a medium dedicated to this topic : https://medium.com/luchadores-chronicles/how-to-create-a-personal-rpc-via-alchemy-5d67d6eef957
- PK: the private key of the operator wallet
- APP_PORT: used to start the back end, still not used to add a dedicated API (in my plans)
- DIAMOND_ADDRESS (0x86935f11c86623dec8a25696e1c19a8659cbf95d): it's an aavegotchi proxy contract to interact with gotchis (you can check it easily on internet)
- ADDRESSES_TO_CHECK: If you want to run the bot for your friends. Currently a wallet can delegate the petting action, so if someone know the public key link to your operator wallet, you will run pet actions for free for him. So ADDRESSES_TO_CHECK is a kind of whitelist
- CRON_PATTERN: the frequency to check if gotchis need a pet action on wallets declated in ADDRESSES_TO_CHECK 

With the DIAMOND_ADDRESS we will use two contracts (diffrents ABI): 
- The gotchi contract: used to handle delegation on petting actions
- The pet contract: used to call the pet action
